packages:
  - apps/*/*
  - components/*
  - examples/*
  - frameworks/*
  - libraries/*
  - plugins/*
  - presets/*
  - tools/*

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

allowBuilds:
  esbuild: true
  fsevents: true

catalog:
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/browser': ^4.1.11
  '@vitest/browser-playwright': ^4.1.11
  '@vitest/coverage-v8': ^4.1.11
  vite: ^7.3.6
  vitest: ^4.1.11
