ignores:
  - '@just-web/repo-scripts'
  - '@repobuddy/typescript' # for build:cjs
  - '@size-limit/*'
  - '@storybook/*'
  - '@testing-library/*'
  - '@types/*'
  - autoprefixer # tailwind
  - eslint*
  - jest-image-snapshot
  - nyc # used by @storybook/addon-coverage
  - rimraf # depcheck doesn't recognize rimraf as a dependency
  - size-limit
  - tailwindcss # tailwind
  - wait-on # sb:ci
