name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      node-version: '[18]'
