name: release
on:
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: "Update snapshots"
        type: boolean
        required: false
        default: false
  push:
    branches: [main]

jobs:
  update_snapshots:
    uses: justland/.github/.github/workflows/pnpm-update-snapshots.yml@main
    with:
      os: '["ubuntu-latest"]'
      node_version: '[18]'
      update_snapshots: ${{ inputs.update_snapshots }}
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    if: ${{ inputs.update_snapshots == false }}
    with:
      os: '["ubuntu-latest"]'
      node-version: '[18]'

  release:
    uses: justland/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit

  # docgen:
  #     uses: justland/.github/.github/workflows/pnpm-docs.yml@main
  #     needs: release
